# Welcome to Jekyll!

# Site settings

title: netinetidesign
email: marcelreig@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Desarrollador front-end Menorca
baseurl: "" # the subpath of your site, e.g. /blog
url: https://www.netinetidesign.com
name: netinetidesign

# Multilanguage
lang: en

# Social
linkedin_path: https://www.linkedin.com/in/marcel-reig/
twitter_path: https://twitter.com/netinetidesign
github_path: https://github.com/MarcelReig
codepen_path: https://codepen.io/MarcelReig
behance_path: https://www.behance.net/netinetidesign
spotify_path: https://play.spotify.com/user/netineti
instagram_path: https://www.instagram.com/netinetidesign

twitter_username: netinetidesign

social_img: social_img.jpg

# Build settings
markdown: kramdown

# Outputting
permalink: /post/:title/
paginate: 6
paginate_path: /blog/page:num/

# Collections
collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/
  my_tags:
    output: true
    permalink: /blog/tag/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: my_categories
    values:
      layout: blog_by_category
  - scope:
      path: ""
      type: my_tags
    values:
      layout: blog_by_tag

include:
  - _redirects

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - gulpfile.js
  - package-lock.json
  - package.json
  - node_modules
  - README.md
  - readme.md
  - CHANGELOG.md

# Hack Para hablar de Jekyll dentro de Jekyll
lcb: "{"
rcb: "}"
double-lcb: "{{"
double-rcb: "}}"

# Google services
google_analytics: UA-120243860-1

# Disqus Comments
disqus:
    shortname: netinetidesign

