# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: netinetidesign
email: marcelreig@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Desarrollador front-end Menorca
baseurl: "" # the subpath of your site, e.g. /blog
url: https://www.netinetidesign.com/
name: netinetidesign

# Social
codepen_path: https://codepen.io/MarcelReig
github_path: https://github.com/MarcelReig
twitter_path: https://twitter.com/netinetidesign
behance_path: https://www.behance.net/netinetidesign
spotify_path: https://play.spotify.com/user/netineti
freecodecamp_path: https://www.freecodecamp.org/marcelreig

twitter_username: netinetidesign

social_img: social_img.jpg

# Build settings
markdown: kramdown

# Plugins
plugins: [jekyll-paginate]

# Outputting
permalink: /post/:title/
paginate: 6
paginate_path: /blog/page:num/

# Collections
collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/
  my_tags:
    output: true
    permalink: /blog/tag/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: my_categories
    values:
      layout: blog_by_category
  - scope:
      path: ""
      type: my_tags
    values:
      layout: blog_by_tag

include:
  - _redirects

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - gulpfile.js
  - package-lock.json
  - package.json
  - node_modules
  - README.md
  - readme.md
  - CHANGELOG.md

# Hack Para hablar de Jekyll dentro de Jekyll
lcb: "{"
rcb: "}"
double-lcb: "{{"
double-rcb: "}}"

# Disqus Comments
disqus:
    shortname: netinetidesign

